name: My YourTomo cat

on:
  schedule:
    - cron: '23 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Debug timezone
        run: |
          echo "Runner UTC:"
          date -u

          echo "Runner local:"
          date

          echo "Expected India time:"
          TZ=Asia/Kolkata date

      - uses: prsdx/github-pet@v1
        with:
          username: manjeetchugh
          timezone-offset-minutes: "330"
          display-name: "Manjeet"
          pet-name: "Typo"
